export { default as Dashboard } from './dashboard/Dashboard'
export { default as AllAppointments } from './appointments/AllAppointments'
export { default as DoctorsManagement } from './users/DoctorsManagement'
export { default as DoctorDetails } from './users/DoctorDetails'
export { default as PatientsManagement } from './users/PatientsManagement'
export { default as PatientDetails } from './users/PatientDetails'
